config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:edit, :update]
  root to: "records#home"
  resources :records
  get 'tag', to: 'records#tag'

  resources :incomes
  get 'top', to: 'incomes#top'
  post "income_values/new(/:name)" => "income_values#new"
  resources :fixedcosts
  resources :variablecosts
  resources :income_values
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :tag_relationships, dependent: :destroy
  has_many :tags, through: :tag_relationships

  with_options presence: true do
    validates :image
    validates :title, length: { maximum: 10 }
    validates :content, length: { maximum: 200 }
  end
  validates :height, allow_blank: true,  numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 999}
  validates :weight, allow_blank: true,  numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 9999}

  def self.records_serach(search)
    Record.where(['title LIKE ? OR content LIKE ?', "%#{search}%", "%#{search}%"])
  end

  def save_tags(saverecord_tags)
    current_tags = self.tags.pluck(:name_tag) unless self.tags.nil?
    old_tags = current_tags - saverecord_tags
    new_tags = saverecord_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name_tag: old_name)
    end

    new_tags.each do |new_name|
      record_tag = Tag.find_or_create_by(name_tag: new_name)
      self.tags << record_tag
    end
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!, except: :home
  before_action :records_find, only: [:index, :show]
  before_action :record_find, only: [:show, :edit, :update, :destroy]
  before_action :user_judge, only: [:edit, :destroy]

  #ホームページ
  def home
  end
  
  #タグ検索ページ
  def tag
    if params[:search].present?
      @records = Record.records_serach(params[:search])
    elsif params[:tag_id].present?
      @tag = Tag.find(params[:tag_id])
      @records = @tag.records.order(created_at: :desc)
    else
      @records = Record.all.order(created_at: :desc)
    end
    @tag_lists = Tag.all
  end

  def index
    @tag_lists = Tag.all
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    tag_list = params[:record][:tag_ids].split(',')
    if @record.save
      @record.save_tags(tag_list)
      redirect_to record_path(@record.id)
    else
      render :new
    end
  end
  
  def show
    @tag_lists = Tag.all
  end

  def edit
    @tag_list =@record.tags.pluck(:name_tag).join(",")
  end

  def update
    tag_list = params[:record][:tag_ids].split(',')
    if @record.update(record_params)
      @record.save_tags(tag_list)
      redirect_to record_path(@record.id)
    else
      render :edit
    end
  end

  def destroy
    @record.destroy
    redirect_to records_path
  end

  private
  def record_params
    params.require(:record).permit(:title, :content, :image, :height, :weight).merge(user_id: current_user.id)
  end

  def records_find
    @records = Record.where(user_id: current_user.id).includes(:user).order(created_at: :desc)
  end

  def record_find
    @record = Record.find(params[:id])
  end

  def user_judge
    redirect_to root_path unless current_user.id == @record.user.id
  end

end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/edit.html.erb
<div class="new-main">
  <header>
    <div class="seichou-header">
        <div class="seichou-title">
          <%= link_to "たけのこ", root_path %>
        </div>
        <div class="seichou-new">
          <%= link_to "もどる", record_path(@record.id) %>
        </div>
    </div>
  </header>
  <div class="contents-new">
    <div class="new">
      <div class="container">
        <%= form_with(model: @record, id: 'record_post', local: true) do |form| %>
          <div class="image-preview">
            <div id="previews"></div>
            <div id="preview-none"><%= image_tag @record.image %></div>
            <div class="image-form"><%= form.file_field :image %></div>
          </div>
          <div><%= form.text_field :title, placeholder: "タイトル", maxlength: "10" %></div>
          <div><%= form.text_area :content, placeholder: "おもいで", maxlength: "200" %></div>
          <div>
            <%= form.text_field :height, placeholder: "しんちょう", maxlength: "3" %>
            <%= form.text_field :weight, placeholder: "たいじゅう", maxlength: "4" %>
          </div>
          <%= form.text_field :tag_ids,value: @tag_list,placeholder: "タグをつける。複数つけるには','で区切ってください。" %>
          <%= form.submit "さくせい" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/records/home.html.erb
<div class="screen">
<header class="header">
      <div class="header_bar">
        <h1 class="header-title">たけのこ</h1>
        <div class="user">
        <% if user_signed_in? %>
          <%= link_to current_user.name, edit_user_path(current_user.id) %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path %>
          <%= link_to "サインアップ", new_user_registration_path %>
        </div>
        <% end %>
      </div>
    </header>

  <div class="home-main">
    <div class="animation-area">
      <div class="overlay"></div>
      <div id='animation'></div>
      <div id="circle">
        <div class="contents one">
          <%= link_to "せいちょうきろく", records_path %>
        </div>
        <div class="contents two">
          <%#= link_to "#" %>
        </div>
        <div class="contents three">
          <%= link_to "かけいぼ", top_path %>
        </div>
        <div class="contents four">
          <%= link_to "めも", "#" %>
        </div>
      </div>
    </div>
  </div>
  <div class="control">
    <%= image_tag 'arrow.png', id: 'upBtn' %>
    <h3>カテゴリー</h3>
    <%= image_tag 'arrow.png', id: 'downBtn' %>
  </div>
</div>

app/views/records/index.html.erb
<div class="seichou">
  <header>
    <div class="seichou-header">
        <div class="seichou-title">
          <%= link_to "たけのこ", root_path %>
        </div>
        <div class="seichou-new">
          <%= link_to "きろくをつくる", new_record_path %>
        </div>
    </div>
  </header>

  <main>
    <div class="seichou-main">
      <div class="main-contents">
        <div class="tag-area">
          <div class="tag-search">
            <% @tag_lists.first(1).each do |list| %>
              <div class="tag-one"><%= link_to "タグで検索する", tag_path(tag_id: list.id) %></div>
            <% end %>
          </div>
        </div>
        <div class="records">
          <div class="memory">おもいで</div>
          <% @records.first(10).each do |record| %>
            <div class="records-content">
            <div class="title-date">
              <%= record.created_at.strftime('%Y/%m/%d')%>
              <%= link_to record.title, record_path(record.id) %>
            </div>
            <div class="record-text"><%= record.content.truncate(50) %></div>
            </div>
          <% end %>
        </div>
        <div class="record">
          <div class="title-date">
          </div>
        </div>
      </div>
    </div>
  </main>

</div>

app/views/records/new.html.erb
<div class="new-main">
  <header>
    <div class="seichou-header">
        <div class="seichou-title">
          <%= link_to "たけのこ", root_path %>
        </div>
        <div class="seichou-new">
          <%= link_to "もどる", records_path %>
        </div>
    </div>
  </header>
  <div class="contents-new">
    <div class="new">
      <div class="container">
        <%= form_with(model: @record, id: 'record_post', local: true) do |form| %>
          <div class="image-preview">
            <div id="previews"></div>
            <div id="preview-none"><%= image_tag "20200501_noimage.png" %></div>
            <div class="image-form"><%= form.file_field :image %></div>
          </div>
          <div><%= form.text_field :title, placeholder: "タイトル", maxlength: "10" %></div>
          <div><%= form.text_area :content, placeholder: "おもいで", maxlength: "200" %></div>
          <div>
            <%= form.text_field :height, placeholder: "しんちょう", maxlength: "3" %>
            <%= form.text_field :weight, placeholder: "たいじゅう", maxlength: "4" %>
          </div>
          <div class="tag-field">
            <%= form.text_field :tag_ids, class: "form-control", id:'tag_ids',placeholder: "タグをつける。複数つけるには','で区切ってください。" %>
          </div>
          <%= form.submit "さくせい" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/records/show.html.erb
<div class="seichou">
  <header>
    <div class="seichou-header">
        <div class="seichou-title">
          <%= link_to "たけのこ", root_path %>
        </div>
        <div class="seichou-new">
          <%= link_to "きろくをつくる", new_record_path %>
        </div>
    </div>
  </header>

  <main>
    <div class="seichou-main">
      <div class="main-contents">
        <div class="tag-area">
          <div class="tag-search">
            <% @tag_lists.first(1).each do |list| %>
              <div class="tag-one"><%= link_to "タグで検索する", tag_path(tag_id: list.id) %></div>
            <% end %>
          </div>
        </div>
        <div class="records">
          <div class="edit-delete">
            <div class="memory">おもいで</div>
            <div class="edit-delete-btn" id="fadein-btn">
              <div><%= link_to "ぬりかえる", edit_record_path(@record.id) %></div>
              <div><%= link_to "けす", record_path(@record.id), method: :delete %></div>
            </div>
            <script>$("#fadein-btn").fadeIn(1000);</script>
          </div>
          <% @records.first(10).each do |record| %>
            <div class="records-content">
              <div class="title-date">
                <%= record.created_at.strftime('%Y/%m/%d')%>
                <%= link_to record.title, record_path(record.id) %>
              </div>
              <div class="record-text"><%= record.content.truncate(50) %></div>
            </div>
          <% end %>
        </div>
        <div class="record">
          <div class="record-width">
            <div class="content" id="fadein-content"><%= simple_format(@record.content) %></div>
            <div class="image" id="fadein-image">
              <%= image_tag @record.image.variant(resize: '500x500') %>
              <div class="record-height-weight">
                <% if @record.height.present? %>
                  <%= "身長:#{@record.height}cm" %>
                <% end %>
                <% if @record.weight.present? %>
                  <% if @record.weight < 1000 %>
                    <%= "体重:#{@record.weight}kg" %>
                  <% else %>
                    <%= "体重:#{@record.weight}g" %>
                  <% end %>
                <% end %>
              </div>
              <div class="show-tag">
              <% @record.tags.each do |tag| %>
                <%= "##{tag.name_tag}" %>
              <% end %>
              </div>
            </div>
            <div class="date-title" id="fadein-title">
                <%= @record.created_at.strftime('%Y/%m/%d') %>
                <%= @record.title %>
            </div>
            <script>$("#fadein-content").fadeIn(1000);</script>
            <script>$("#fadein-image").fadeIn(1000);</script>
            <script>$("#fadein-title").fadeIn(1000);</script>
          </div>
        </div>
      </div>
    </div>
  </main>

</div>

app/views/records/tag.html.erb
<div class="tag-page">

  <header class="tag-header">
    <div class="tag-header-bar">
      <div class="tag-header-title"><%= link_to "たけのこ", root_path %></div>
      <div class="tag-header-back"><%= link_to "もどる", records_path %></div>
    </div>
  </header>

  <div class="tag-contents">

    <div class="tag-side">
      <div class="tag-lists">
        <div class="tag-side-title">タグリスト</div>
        <div class="tag-side-tags">
          <% @tag_lists.each do |list| %>
            <div class="tags">
              <%= link_to list.name_tag, tag_path(tag_id: list.id) %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="tag-main">
      <div class="tag-records-title"><%= "##{@tag.name_tag}のおもいで" %></div>
      <div class="tag-records">
        <% @records.each do |record| %>
          <div class="tag-record-title"><%= record.title %></div>
          <div class="tag-image"><%= image_tag record.image.variant(resize: '500x500') %></div>
          <div>
            <% if record.height.present? %>
              <%= "身長:#{record.height}cm" %>
            <% end %>
            <% if record.weight.present? %>
              <% if record.weight < 1000 %>
                <%= "体重:#{record.weight}kg" %>
              <% else %>
                <%= "体重:#{record.weight}g" %>
              <% end %>
            <% end %>
          </div>
          <div class="tag-record-content"><%= record.content %></div>
          <div><%= record.created_at.strftime('%Y/%m/%d') %></div>
          <div class="tag-record-tag">
            <% record.tags.each do |tag| %>
              <%= "##{tag.name_tag}" %>
            <% end %>
          </div>
          <div class="tag-edit-delete">
            <%= link_to "ぬりかえる", edit_record_path(record.id) %>
            <%= link_to "けす", record_path(record.id), method: :delete %>
          </div>
        <% end %>
      </div>
    </div>

  </div>

</div>